# Generated by Django 3.0.5 on 2020-05-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200506_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgurl',
            field=models.URLField(default='url'),
        ),
    ]
