# Generated by Django 3.0.5 on 2020-05-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_imgurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imgurl',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
