# Generated by Django 3.0.6 on 2020-05-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160),
        ),
    ]
